/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DemoConsoleRouteImport } from './routes/demo-console'
import { Route as CompleteSessionRouteImport } from './routes/complete-session'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicPinchWebhookRouteImport } from './routes/api/public/pinch-webhook'

const DemoConsoleRoute = DemoConsoleRouteImport.update({
  id: '/demo-console',
  path: '/demo-console',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteSessionRoute = CompleteSessionRouteImport.update({
  id: '/complete-session',
  path: '/complete-session',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPinchWebhookRoute = ApiPublicPinchWebhookRouteImport.update({
  id: '/api/public/pinch-webhook',
  path: '/api/public/pinch-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/complete-session': typeof CompleteSessionRoute
  '/demo-console': typeof DemoConsoleRoute
  '/api/public/pinch-webhook': typeof ApiPublicPinchWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/complete-session': typeof CompleteSessionRoute
  '/demo-console': typeof DemoConsoleRoute
  '/api/public/pinch-webhook': typeof ApiPublicPinchWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/complete-session': typeof CompleteSessionRoute
  '/demo-console': typeof DemoConsoleRoute
  '/api/public/pinch-webhook': typeof ApiPublicPinchWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/complete-session'
    | '/demo-console'
    | '/api/public/pinch-webhook'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/complete-session' | '/demo-console' | '/api/public/pinch-webhook'
  id:
    | '__root__'
    | '/'
    | '/complete-session'
    | '/demo-console'
    | '/api/public/pinch-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompleteSessionRoute: typeof CompleteSessionRoute
  DemoConsoleRoute: typeof DemoConsoleRoute
  ApiPublicPinchWebhookRoute: typeof ApiPublicPinchWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/demo-console': {
      id: '/demo-console'
      path: '/demo-console'
      fullPath: '/demo-console'
      preLoaderRoute: typeof DemoConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete-session': {
      id: '/complete-session'
      path: '/complete-session'
      fullPath: '/complete-session'
      preLoaderRoute: typeof CompleteSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pinch-webhook': {
      id: '/api/public/pinch-webhook'
      path: '/api/public/pinch-webhook'
      fullPath: '/api/public/pinch-webhook'
      preLoaderRoute: typeof ApiPublicPinchWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompleteSessionRoute: CompleteSessionRoute,
  DemoConsoleRoute: DemoConsoleRoute,
  ApiPublicPinchWebhookRoute: ApiPublicPinchWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
